### ISSUE TITLE
Weblate: Community based Adapter Translations

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/Community#1]
**Status:** In Progress
**Owner:** @UncleSamSwis
**Link:** https://weblate.iobroker.net
**Documentation:** TBD

**Description:**
This initiative has the goal to allow more easy translation of adapters to allow the community to support it .....

**Next steps:**
...

**Comment by UncleSamSwiss** [comment]
Weblate ist nun "offiziell": https://forum.iobroker.net/topic/42820/entwicklungs-tool-adapter-%C3%BCbersetzungen-neu-mit-weblate
Bitte an alle Entwickler: [beantragt](https://github.com/ioBrokerTranslator/requests/issues/new/choose) eure Aufnahme.

**Comment by Apollon77** [comment]
* Status 21.4.21: 40 Adapters in weblate, 15 more to come in teh next days, after this we go out and try to get translators

**Comment by UncleSamSwiss** [comment]
I think we can now close this. Weblate is working, we have many of the top adapters in it and every now and then another developer requests to add his adapter(s) to Weblate. @Apollon77 do you agree?

**Comment by Apollon77** [comment]
Istill have 30 on my list but will come as we come to it... but yes, I would close wednesday in dev meeting :-)
