### ISSUE TITLE
Benchmark Adapter

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/Community#13]
**Status:** Concept
**Owner:** TBD
**Link:** TBD
**Documentation:** TBD

**Description:**
The idea is to implement a benchmark adapter to be able to get some statistic infos for the js-controller and a host. This should allow to compare the performance of js-controller changes, but also allows to compare different types of systems.

**Next steps:**
...

**Comment by foxriver76** [comment]
I would think like writing `n` states/objects/(maybe files), measuring the needed time/cpu/ram for each.

@Apollon77 I think you have many additional ideas

**Comment by GermanBluefox** [comment]
We thought about creation of states (e.g. 10000 and measure it), writing of states (e.g. every 3 seconds every third state and measure it), reading the states (measure it) and deletion of states and measure it.
And this with Value-Validation and without. 
With these 4 steps the special index must be calculated: e.g
- reading 0.4
- writing 0.3
- creation 0.2
- deletion 0.1

And then to calculate the ioNdex and to have a button "Publish". CPU, RAM, OS (whatever else) will be shown in common public table. So the people will know the best system :)

**Comment by foxriver76** [comment]
What is meant by without validation and with? Requiring the database classes directly instead of using adapter methods? Or just w/o strictObjectChecks

Also I don't get the 3 second stuff. I would e.g. do eg 10,000 state sets for 5 epochs, measuring time of each epoch and at the end giving mean and std.

Also absolutely not sure about this scores, should they always sum up to 1? Why no absolute values, to be honest, it would be clearer to me.

**Comment by Apollon77** [comment]
In fact there are two topics in here (and yes I still need to find my notes):

1.) What to measure
2.) How to measure

The main idea was to have a modular approach.

to 1)
On one hand we could offer "test modules" that are doing stuff and also measuring it. The modules should have a "prepare" step (e.g. create 1mio objects), an actual "test" step (write 1mio state values), pot a measurement part (or that is integrated in the test step, but maybe better separate) and a "cleanup" step (remove the 1 mio objects again).
And then we have different tests depending on what we want:
* precreate objects and write states ... how many states/s are written
* precreate objects and write states - subscribe and measure on the "subscription receiving site" incl. verification that all came through
* create objects incl./excl. default state value ... how many objects/s are written
* create objects incl./excl. default state value ... subscribe and measure "subscription receiving site" 
* precreate 1mio objects and measure delete object performance

So some of them have a "generator process" and a "subscription process", so not all tests have the same. It also depends on what you want to check. we have a sending side, the DB that need to "store and process" it and pot send it out to subscribers and we have the subscriber. So it depends on the "measurement question" on what to focus the tests.

I would measure the adapter.js methods used because these are basically used by all adapters ad not plain DB.

With this we could easiely add new tests when we find them interesting in just wrote some lines of javascript in a new file.

zu 2.) 
While we did some analysis with controller 2.0 (after the redis protocol change) we alreayd learned that the way we measured it before (usse javascript adapter) do not make that much of a sense because too much happens there.

So the idea is that the adapter have two modes: The "Test contoller" mode and the "Test processor" mode. And in fact you simply create multiple instances on need. Idea was to select a testcase in the controller and enter some values to configure stuff or such and then hit "execute". Depending on the settings the adater creates new instances in "processor" mode which are peconfigured to execute and pot. monitor the test. at the end the instances get cleaned up again and test result is stored on "controller".

So you can do different tests like:
* "bombing setState from 4 instances with rate X to one subscribing instance and measure where the "receiving" limit is". 
* Or how a multihost system then behaves different from single host when having the instances split more. 
* Or you want to test the throughput of the DB, so maybe you start N generator-subscriber pairs so that these can not be the bottleneck to check on DB throughput
* Or just have one instance and see how many setState are written per timeframe (mainly executed by doing setState 10000 times and measure how long it took). 

Target groups for the adapter: Here we have a small "conflict". One one hand we want a tool to measure changes and their effects on controller and compare e.g. fileDB and Redis or such. All that to optimize for users and to know the limits. For that I could also live with a "json" to configure a test and no fancy UI :-)

The other target group is "the community" that needs a simply way to execute "a default testcombination-case" that measures overall performance of a system in a "Non destructive" way and allow a comparism between different HW and OS versions or such. I'm not sure if this will ever be comparable but other story :-)

**Comment by GermanBluefox** [comment]
> Or just w/o strictObjectChecks

Yes
