### ISSUE TITLE
influxdb 2.x Support for influxdb Adapter

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/Community#16]
**Status:** Concept
**Owner:** @Excodibur
**Link:** will be new PR in influxdb repo
**Documentation:** InfluxDB compatibility Wrapper for new Libary and so support influxdb 1.9 and 2.x

**Description:**
The influxdb adapter needs a rewrite to support influxdb 2.x

**Next steps:**
* Reveiw PR
* Test

**Comment by Excodibur** [comment]
Pull Request here: https://github.com/ioBroker/ioBroker.influxdb/pull/99
