### ISSUE TITLE
Notification Communication Hub Adapter

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/Community#19]
**Status:** Idea
**Owner:** TBD
**Link:** TBD
**Documentation:** TBD

**Description:**
The idea is to provide an adapter that checks for notifications and maybe adds more configurable notification options (e.g. loglevel based or such or interact with other Adapters like LogParser and such) and allows to specify which kidnof message should be notified to the user how - e.g. Telegram/Whatsapp/Email/SMS(later)/Phone call(later) ...
Ideally we also implement a way to detect if once communication channelis not possible (e.g. telegram not possible because no internet, send important errors as SMS).

So beside creating such an adapter also part would be to check the other communication adapter to get error callbacks on errors

**Next steps:**
...

**Comment by foxriver76** [comment]
On my List. I have no power here so you can assign me @Apollon77 😬

**Comment by foxriver76** [comment]
can be closed as done
