### ISSUE TITLE
Official Docker Image powered by buanet

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/Community#2]
**Status:** In Progress
**Owner:** @buanet
**Link:** TBD
**Documentation:** TBD

**Description:**
This initiative aims to provide an official ioBroker docker image based on the awesome buanet images ...
?? Also provide links to FAQ and troublesooting resources for iobroker homepage

**Next steps:**
...

**Comment by Apollon77** [comment]
Open:
* Info on Docker Hub page https://hub.docker.com/r/iobroker/iobroker
* Docker short doku iobroker webseite mit Links

**Comment by buanet** [comment]
My plan is to move the image with upcoming v6 image version (and node 14) from buanet/iobroker to iobroker/iobroker.

**Comment by Excodibur** [comment]
@buanet: Any thoughts on building and pushing the Docker images with Github Actions automatically upon tagging new releases? With Qemu building for multiple architectures should also be relatively easy.

This would also increase transparency.
