### ISSUE TITLE
Auto generated Raspi Images

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/Community#3]
**Status:** In Progress
**Owner:** @buanet
**Link:** TBD
**Documentation:** TBD

**Description:**
This initiative aims to provide current raspberry images with low efforts by automatically generating them and providing them for download.

**Next steps:**
...

**Comment by Apollon77** [comment]
Open:
* Download/Storage location?
* Docu und Download page

**Comment by buanet** [comment]
* Image is now available for download from https://www.iobroker.net/#de/download
* Image will be automatically generated and pushed once a week (every Tuesday)
