### ISSUE TITLE
React based Configurable Adapter Config 

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/Community#4]
**Status:** In Progress
**Owner:** @frankjoke, @GermanBluefox 
**Link:** TBD
**Documentation:** TBD

**Description:**
This initiative aims to provide a configurable adapter configuration to allow building easier adapter config pages. Afterthat it should be integrated as feature in Admin 5

**Next steps:**
...

**Comment by frankjoke** [comment]
Hi Ingo, own version nearly finished, need help to make it a simple package.

**Comment by UncleSamSwiss** [comment]
The very simple UI is waiting for a discussion and feedback from @GermanBluefox here:
https://github.com/ioBroker/ioBroker.admin/pull/664

**Comment by Apollon77** [comment]
* Admin5 will have an integrated solution: https://github.com/ioBroker/ioBroker.admin/blob/master/src-rx/src/components/JsonConfigComponent/SCHEMA.md (JSON schema in writing by @foxriver76
* @frankjoke cleaned out the second option: https://github.com/frankjoke/adapterconfig
